version: '3'

services:
  phoenix:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "80:80"

